### ISSUE TITLE
repo doesn't contain whole vosk model

### ISSUE THREAD

**Issue by AlexC-ux** [VladS23/TgAdmBot#11]
i think we need to **add git-lfs** for lost files

@VladS23 
( files which not included in #10 )

**Comment by AlexC-ux** [comment]
model does not load if I "git clone"
I have to download from [here](https://alphacephei.com/vosk/models) and add it myself

**Comment by AlexC-ux** [comment]
### These files

![not_included_files](https://user-images.githubusercontent.com/55258939/209364550-4fac7821-efe8-43bd-b9fb-2c10aa9008cf.png)

**Comment by VladS23** [comment]
added git-lfs.
now tou can run "git lfs clone [url.git]" to clone repo with lfs files/
