### ISSUE TITLE
prvt улучшения

### ISSUE THREAD

**Issue by VladS23** [VladS23/TgAdmBot#60]
1. Добавить возможность просмотра собственного сообщения
2. Добавить указание на  то от кого это сообщение 
3.  В подписи о том каким пользователям можно/нельзя просматривать сообщения необходимо использовать ники из беседы 
4.  Желательно чтобы автор сообщения в этой подписи не дублировался
5.  Добавить возможность отправлять приватные сообщения через лс бота "/prvt режим идЧата пользователи сообщения" (ВАЖНО необходимо учитывать а) существует ли чат б) состоит ли в нем пользователь в) состоят ли в нем адресаты)
6. Возможно стоит добавить проверку из пункта б и в основной код
P.S Занялся бы сам, но не раньше пятницы

**Comment by AlexC-ux** [comment]
- [X] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6

**Comment by AlexC-ux** [comment]
@VladS23 нужно просто брать списке через экземпляр Database.Chat и тогда ничего дополнительно проверять не нужно

**Comment by AlexC-ux** [comment]
#62
